config/routes.rb
Sparkwall::Application.routes.draw do

  root :to => 'main#index'

  get "main/index"

  get 'popular' => 'main#popular'
  get 'about' => 'main#about'
  get 'policy' => 'main#policy'

  resources :comments
  resources :likes#, only: [:create, :destroy]
  resources :grade_levels

  resources :projects do
    collection do
      get :search
    end

    member do
      get :add_to_wishlist
      get :remove_from_wishlist
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"} do
    get 'users/:id' => 'users#show'
  end

  resources :users, :only => [:show, :wishlist, :likes] do
    member do
      get 'wishlist'
      get 'likes'
    end
  end

  get 'tagged' => 'projects#tagged', :as => 'tagged'
  get 'reaction' => 'projects#reaction_tagged', :as => 'reaction_tagged'

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :projects, dependent: :destroy
	has_many :comments, dependent: :destroy
	#has_many :likes
	has_one :wishlist, dependent: :destroy

	has_many :likes, dependent: :destroy
    has_many :liked_projects, :through => :likes, :source => :project

	mount_uploader :avatar, AvatarUploader

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def added_project_to_wishlist?(project)
    	!!wishlist.projects.include?(project)
    end

	def add_to_wishlist(project)
    	wishlist.projects << project
    	wishlist.save
 	end

 	def remove_from_wishlist(project)
 		wishlist.projects.delete(project)
 		wishlist.save
 	end

 	def likes_project?(project)
    	!!likes.find_by(user_id: self.id, project_id: project.id)
 	end

  	def like!(project)
    	likes.create!(project_id: project.id)
  	end

  	def unlike!(project)
    	likes.find_by(project_id: project.id).destroy
  	end

    def is_owner?(project)
      project.user.id == self.id
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

	def resource_params
	  params.require(:user).permit(:username, :name, :email, :location, :password, :password_confirmation, :avatar, :school)
	end

	def sign_up_params
		params.require(:user).permit(:username, :name, :email, :location, :password, :password_confirmation, :avatar, :school)
	end

	def account_update_params
		params.require(:user).permit(:username, :name, :email, :location, :password, :password_confirmation, :avatar, :current_password, :school)
	end

  def new
    build_resource({})
    respond_with self.resource
  end

  # def show
  #   @user = User.find(params[:id])
  # end

  def create
    build_resource(sign_up_params)
    resource.build_wishlist

    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end


  private :resource_params
  private :sign_up_params
  private :account_update_params

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    	@user = User.find(params[:id])
    end

    def wishlist
    	@user = User.find(params[:id])
    end
    
    def likes
    	@user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_header.html.erb
<header class="headerMypage unit-row">
        <div class="unit-80">
            <div class="mypageIcon"><%= image_tag @user.avatar, size: "80" %></div>
            <div class="mypageInfo">
                <ul>
                    <li class="mypageName"><%= @user.username %></li>
                    <li class="mypageLocation">from <%= @user.location %></li>
                    <% if @user.school != nil %>
                        <li class="mypageSchool"><img src="/assets/icon_school.png" height="16" width="16" alt=""><%= @user.school %></li>
                    <% end %>
                </ul>
            </div>
        </div>
        <div class="unit-20">
            <ul class="mypageSetting">
                <li><%= link_to "#{image_tag"icon_setting.png", size: "28"}Settings".html_safe, edit_user_registration_path(@user) %></li>
                <li><%= link_to "#{image_tag"icon_logout.png", size: "28"}Log Out".html_safe, destroy_user_session_path, :method => :delete %></li>
            </ul>
        </div>
        <div class="mypageNav">
            <ul>
                <li class="uploaded"><%= link_to user_path do %>
                	Uploaded <span class="num"><%= @user.projects.count %></span>
                <% end %> </li>

                <li class="wishlist"><%= link_to wishlist_user_path do %>
                	Wishlist <span class="num"><%= @user.wishlist.projects.count %></span>
               <% end %> </li>

                <li class="liked"><%= link_to likes_user_path do %>
                	Liked <span class="num"><%= @user.liked_projects.count %></span>
                <% end %> </li>

            </ul>
        </div>
</header>

app/views/users/likes.html.erb
<div class="unit-80 mainContent">
    <!-- content -->

    <%= render 'user_header' %>

    <%= render '/shared/big_grid_view', :project_collection => @user.liked_projects %>

</div>

app/views/users/show.html.erb
<div class="unit-80 mainContent">
    <!-- content -->

    <%= render 'user_header' %>

    <%= render '/shared/big_grid_view', :project_collection => @user.projects.sort_by{:created_at}.reverse %>

</div>

app/views/users/wishlist.html.erb
<div class="unit-80 mainContent">
    <!-- content -->

    <%= render 'user_header' %>

    <%= render '/shared/big_grid_view', :project_collection => @user.wishlist.projects %>

</div>