config/routes.rb
Sparkwall::Application.routes.draw do

  root :to => 'main#index'

  get "main/index"

  get 'popular' => 'main#popular'
  get 'about' => 'main#about'
  get 'policy' => 'main#policy'

  resources :comments
  resources :likes#, only: [:create, :destroy]
  resources :grade_levels

  resources :projects do
    collection do
      get :search
    end

    member do
      get :add_to_wishlist
      get :remove_from_wishlist
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"} do
    get 'users/:id' => 'users#show'
  end

  resources :users, :only => [:show, :wishlist, :likes] do
    member do
      get 'wishlist'
      get 'likes'
    end
  end

  get 'tagged' => 'projects#tagged', :as => 'tagged'
  get 'reaction' => 'projects#reaction_tagged', :as => 'reaction_tagged'

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates_presence_of :header, :description, :image, :user_id, :reaction_list, :reflection, :tag_list

	has_many :comments, :dependent => :destroy
	
	#has_many :likes
	has_many   :likes, :dependent => :destroy
    has_many   :liked_by, :through => :likes, :source => :user

	#has_many :projects_wishlists
	#has_many :wishlists, :through => :project_wishlists
	has_and_belongs_to_many :wishlists

	belongs_to :user
	belongs_to :grade_level

	mount_uploader :image, ImageUploader
	
	acts_as_taggable
	acts_as_taggable_on :tags, :subjects, :reactions

	def popular_count
		self.liked_by.count + self.wishlists.count
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index, :search, :tagged]  

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  # def like
  #   @project = Project.find(params[:id])
  #   type = params[:type]  

  #   if current_user.liked_project?(@project)
  #     current_user.like!(@project)
  #     redirect_to :back, notice: 'You favorited #{@project.name}'

  #   elsif current_user.liked_project?(@project) == false
  #     current_user.unlike!(@project)
  #     redirect_to :back, notice: 'Unfavorited #{@project.name}'

  #   else
  #     redirect_to :back, notice: 'Nothing happened.'
  #   end

  # end

  def add_to_wishlist
    @project = Project.find(params[:project_id])
    current_user.add_to_wishlist(@project)
    respond_to do |format|
      format.js
      format.html { redirect_to :back }
      #format.json { render action: 'show', status: :created, location: @like }
    end
  end

  def remove_from_wishlist
    @project = Project.find(params[:project_id])
    current_user.remove_from_wishlist(@project)
    respond_to do |format|
      format.js
      format.html { redirect_to :back }
      #format.json { render action: 'show', status: :created, location: @like }
    end
  end

  def tagged
    if params[:tag].present? 
      @projects = Project.tagged_with(params[:tag])
      @tags = params[:tag]
    else 
      @projects = Project.postall
    end  
  end

  def reaction_tagged
    if params[:reaction].present? 
      @projects = Project.tagged_with(params[:reaction], :on => :reactions)
      @tags = params[:reaction]
    else 
      @projects = Project.postall
    end 
  end

  def search
      # @projects = Project.where(["title LIKE ? or description LIKE ?" , "%#{params[:project][:title]}%", "%#{params[:project][:title]}%"])
      @projects = Project.where("header LIKE ?", params[:query])
      render "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:header, :description, :image, :user_id, :tag_list, :reaction_list, :reflection)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/projects/_add_to_wishlist.html.erb
<%= form_tag(add_to_wishlist_project_path(project), method: :get, remote: true) do %>
	<%= hidden_field_tag :project_id, project.id %>
  <%= image_submit_tag("icon_repost.png") %>
<% end %>

app/views/projects/_form.html.erb
<% form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= image_tag(@project.image_url) if @project.image? %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for(@project) do |f| %>
    <h2>What’s your project?</h2>

    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <dl class="units-row units-split">
        <dt class="unit-20">Header*</dt>
        <dd class="unit-80"><%= f.text_field :header %></dd>
        <dt class="unit-20">Picture</dt>
        <dd class="unit-80">
            <div class="file">
              Choose file...
              <%= f.file_field :image %>
            </div>
        </dd>
        <dt class="unit-20" style="margin-bottom: 20px;">Description*</dt>
        <dd class="unit-80" style="margin-bottom: 20px;"><%= f.text_area(:description) %></dd>

        <dt class="unit-20" style="margin-bottom: 20px;">Reflection*</dt>
        <dd class="unit-80" style="margin-bottom: 20px;"><%= f.text_area(:reflection) %></dd>

        <dt class="unit-20">Tags*</dt>
        <dd class="unit-80"><%= f.text_field :tag_list %></dd>

        <dt class="unit-20">Reactions*</dt>
        <dd class="unit-80"><%= f.text_field :reaction_list %></dd>
    </dl>

    <div class="sent">
        <%= f.submit %>
    </div>
  <% end %>

app/views/projects/_like.html.erb
<%= form_for(current_user.likes.build(project_id: project.id), remote: true) do |f| %>
	<div>
		<%= f.hidden_field :project_id %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
	</div>

  	<button type="submit" class="like">
  		<i class="fa fa-thumbs-o-up fa-2x"></i> 
  	</button>

<% end %>

app/views/projects/_like_form.html.erb
<!-- http://ruby.railstutorial.org/chapters/following-users#code-follow_form_partial
 -->
 <% if user_signed_in? %>
	<div id="like_form_<%= project.id %>">
	  <% if current_user.likes_project?(project) %>
	    <%= render 'unlike', project: project %>
	  <% else %>
	    <%= render 'like', project: project %>
	  <% end %>
	</div>
<% end %>

app/views/projects/_remove_from_wishlist.html.erb
<%= form_tag(remove_from_wishlist_project_path(project), method: :get, remote: true) do %>
	<%= hidden_field_tag :project_id, project.id %>
  <%= image_submit_tag("icon_reposted.png") %>
<% end %>

app/views/projects/_unlike.html.erb
<%= form_for(current_user.likes.find_by(project_id: project.id),
             html: { method: :delete }, remote: true) do |f| %>

	<button type="submit" class="unlike">
  		<i class="fa fa-thumbs-o-up fa-2x"></i> 
  	</button>

<% end %>

app/views/projects/_wishlist_form.html.erb
 <% if user_signed_in? %>
	<div id="wishlist_form_<%= project.id %>">
	  <% if !!current_user.added_project_to_wishlist?(project) %>
	    <%= render '/projects/remove_from_wishlist', project: project %>
	  <% else %>
	  	<%= render '/projects/add_to_wishlist', project: project %>
	  <% end %>
	</div>
<% end %>

app/views/projects/edit.html.erb
<div class="unit-80 mainContent contact">

<%= render 'form' %>

</div>

app/views/projects/index.html.erb
<div class="unit-80 mainContent">

<%= form_tag("/projects/search", method: "get") do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Description</th>
      <th>Image url</th>
      <th>User</th>
      <th>Tags</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.header %></td>
        <td><%= project.description %></td>
        <td><%= project.image %></td>
        <td><%= project.user_id %></td>
        <td>
          <% project.tags.any? %>
          <% project.tags.each do |tag| %>
            <%= link_to tag.name, tagged_url(:tag => tag.name) %>
          <% end %>
        </td>
        <td>
          <strong id="liked_by_<%= project.id %>">
            <%= project.liked_by.count %>
          </strong>
        </td>
        <td><%= render '/shared/like_form', :project => project %></td>
        <td><%= render '/shared/wishlist_form', :project => project %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

</div>

app/views/projects/new.html.erb
<!-- <h1>New project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %> -->

<div class="unit-80 mainContent contact">
    <!-- content -->
    <%= render 'form' %>
</div>

app/views/projects/reaction_tagged.html.erb
<div class="unit-80 mainContent">
  <h1>Listing projects tagged <%= @tags %></h1>

  <table>
    <thead>
      <tr>
        <th>Header</th>
        <th>Description</th>
        <th>Image url</th>
        <th>User</th>
        <th>Tags</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.header %></td>
          <td><%= project.description %></td>
          <td><%= project.image %></td>
          <td><%= project.user_id %></td>
          <td>
            <% project.tags.any? %>
            <% project.tags.each do |tag| %>
              <%= link_to tag.name, tagged_url(:tag => tag.name) %>
            <% end %>
          </td>
          <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/remove_from_wishlist.js.erb
$("#wishlist_form_<%= @project.id %>").html("<%= escape_javascript(render :partial => 'projects/add_to_wishlist', :locals => {:project => @project}) %>")
$("#wishlisted_by_<%= @project.id %>").html('<%= @project.wishlists.count %>')

app/views/projects/show.html.erb
<div class="unit-80 mainContent entry">
    <!-- content -->
    <div class="units-row">
        <div class="unit-80">
            <h2>
                <span class="mainTitle"> <%= @project.header %></span>
            </h2>
            <div class="entryImg">
                <%= image_tag @project.image %>
            </div>
            <div class="entryBody">
                <p><%= @project.description %></p>
                <p><%= @project.reflection %></p>
            </div>
        </div>
        <div class="unit-20 entSide">
            <div class="entAuthor">
                <%= image_tag @project.user.avatar, size: "80" %>
                <h3 class="entAuthorName"><%= @project.user.username %></h3>
                <span class="entAuthorLocation">from <%= @project.user.location %></span>
            </div>

            <div class="engTags">
                <h4>Tags</h4>
                <ul>
                    <% @project.tags.each do |tag| %>
                      <li><%= link_to tag.name, tagged_url(:tag => tag.name) %></li>
                    <% end %>
                </ul>
            </div>

            <% if user_signed_in? %>
            <% if current_user.is_owner?(@project) %>
              <div class="userControls">
                <ul>
                  <li><%= link_to "Edit project", edit_project_path(@project) %></li>
                  <li><%= link_to "Delete project", project_path(@project), :method => :delete %></li>
                </ul>
              </div>
            <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/projects/tagged.html.erb
<div class="unit-80 mainContent">
  <h1>Listing projects tagged <%= @tags %></h1>

  <table>
    <thead>
      <tr>
        <th>Header</th>
        <th>Description</th>
        <th>Image url</th>
        <th>User</th>
        <th>Tags</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.header %></td>
          <td><%= project.description %></td>
          <td><%= project.image %></td>
          <td><%= project.user_id %></td>
          <td>
            <% project.tags.any? %>
            <% project.tags.each do |tag| %>
              <%= link_to tag.name, tagged_url(:tag => tag.name) %>
            <% end %>
          </td>
          <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Project', new_project_path %>
</div>