config/routes.rb
Sparkwall::Application.routes.draw do

  root :to => 'main#index'

  get "main/index"

  get 'popular' => 'main#popular'
  get 'about' => 'main#about'
  get 'policy' => 'main#policy'

  resources :comments
  resources :likes#, only: [:create, :destroy]
  resources :grade_levels

  resources :projects do
    collection do
      get :search
    end

    member do
      get :add_to_wishlist
      get :remove_from_wishlist
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"} do
    get 'users/:id' => 'users#show'
  end

  resources :users, :only => [:show, :wishlist, :likes] do
    member do
      get 'wishlist'
      get 'likes'
    end
  end

  get 'tagged' => 'projects#tagged', :as => 'tagged'
  get 'reaction' => 'projects#reaction_tagged', :as => 'reaction_tagged'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :project

end

app/models/grade_level.rb
class GradeLevel < ActiveRecord::Base
	has_many :projects
end

app/models/like.rb
class Like < ActiveRecord::Base

	belongs_to :user
	belongs_to :project

	validates :user_id, presence: true
 	validates :project_id, presence: true

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates_presence_of :header, :description, :image, :user_id, :reaction_list, :reflection, :tag_list

	has_many :comments, :dependent => :destroy
	
	#has_many :likes
	has_many   :likes, :dependent => :destroy
    has_many   :liked_by, :through => :likes, :source => :user

	#has_many :projects_wishlists
	#has_many :wishlists, :through => :project_wishlists
	has_and_belongs_to_many :wishlists

	belongs_to :user
	belongs_to :grade_level

	mount_uploader :image, ImageUploader
	
	acts_as_taggable
	acts_as_taggable_on :tags, :subjects, :reactions

	def popular_count
		self.liked_by.count + self.wishlists.count
	end

end

app/models/projects_wishlist.rb
class ProjectsWishlist < ActiveRecord::Base
	belongs_to :project
	belongs_to :wishlist
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :projects, dependent: :destroy
	has_many :comments, dependent: :destroy
	#has_many :likes
	has_one :wishlist, dependent: :destroy

	has_many :likes, dependent: :destroy
    has_many :liked_projects, :through => :likes, :source => :project

	mount_uploader :avatar, AvatarUploader

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def added_project_to_wishlist?(project)
    	!!wishlist.projects.include?(project)
    end

	def add_to_wishlist(project)
    	wishlist.projects << project
    	wishlist.save
 	end

 	def remove_from_wishlist(project)
 		wishlist.projects.delete(project)
 		wishlist.save
 	end

 	def likes_project?(project)
    	!!likes.find_by(user_id: self.id, project_id: project.id)
 	end

  	def like!(project)
    	likes.create!(project_id: project.id)
  	end

  	def unlike!(project)
    	likes.find_by(project_id: project.id).destroy
  	end

    def is_owner?(project)
      project.user.id == self.id
    end
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
	belongs_to :user
	#has_many :project_wishlists
	#has_many :projects, :through => :projects_wishlists
	has_and_belongs_to_many :projects
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :project_id, :user_id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create

    @project = Project.find(params[:like][:project_id])
    current_user.like!(@project)

    respond_to do |format|
      format.js
      format.html { redirect_to :back }
      format.json { render action: 'show', status: :created, location: @like }
    end

  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @project = Like.find(params[:id]).project
    current_user.unlike!(@project)

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:user_id, :project_id)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def welcome
  end

  def about
  end

  def popular
  end

  def policy
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    	@user = User.find(params[:id])
    end

    def wishlist
    	@user = User.find(params[:id])
    end
    
    def likes
    	@user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grade_levels_helper.rb
module GradeLevelsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sparkwall</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>

<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div id="topBorder"></div>

    <div class="units-row">
        <div class="unit-20 side">
            <!-- sidebar -->
            <!--logo-->
            <h1 id="logo"><%= link_to image_tag("logo.png"), root_path %></h1>
            <!--logo--> 
            <!--nav-->
            <div class="sideNav">
                <% if user_signed_in? %>
                <h2><%= current_user.username %></h2>
                <nav>
                    <ul>
                        <li><%= link_to "My Profile", user_path(current_user) %></li>
                        <li><%= link_to "Wishlist", wishlist_user_path(current_user) %></li>
                        <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                    </ul>
                    <% else %>
                    <ul>
                        <li><b><%= link_to "Sign Up", new_user_registration_path %></b></li>
                        <li><%= link_to "Log in", new_user_session_path %></li>
                    </ul>
                    <% end %>
                    <ul>
                       <li><%= link_to "About", about_path %></li>
                       <!--li><a href="#">Facebook</a></li-->
                       <!--li><a href="#">Twitter</a></li-->
                   </ul>
               </nav>
               <nav>
                   <ul>
                      <li><%= link_to "Browse", root_path %></li>
                      <li><%= link_to "Popular", popular_path %></li>
                       <!--li><a href="#">Random</a></li-->
                   </ul>
               </nav>
               <h2>Trending</h2>
               <nav>
                   <ul>
                       <li><a href="#">Lorern</a></li>
                       <li><a href="#">Ipsum</a></li>
                       <li><a href="#">Sit Amet</a></li>
                   </ul>
               </nav>
           </div>
       </div>
       <%= yield %>
   </div>

   <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
   <script>
       $(function(){
         $(".content").click(function(){
            window.location=$(this).find("a.postLink").attr("href");
            return false;
          });
        });

        $(function(){
            $(".content span").click(function(e){
              e.stopPropagation();
              //show tooltip
            });
        });

        $(function(){
            $(".action").click(function(e){
              e.stopPropagation();
              //show tooltip
            });
        });

        $(function(){
            $(".contentHash").click(function(e){
              e.stopPropagation();
              //show tooltip
            });
        });

    </script
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sparkwall</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>

<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div id="topBorder"></div>

    <div class="units-row">
        <div class="unit-20 side">
            <!-- sidebar -->
            <!--logo-->
            <h1 id="logo"><%= link_to image_tag("logo.png"), root_path %></h1>
            <!--logo--> 
            <!--nav-->
            <div class="sideNav">
                <% if user_signed_in? %>
                <h2><%= current_user.username %></h2>
                <nav>
                    <ul>
                        <li><%= link_to "My Profile", user_path(current_user) %></li>
                        <li><%= link_to "Wishlist", wishlist_user_path(current_user) %></li>
                        <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                    </ul>
                    <% else %>
                    <ul>
                        <li><b><%= link_to "Sign Up", new_user_registration_path %></b></li>
                        <li><%= link_to "Log in", new_user_session_path %></li>
                    </ul>
                    <% end %>
                    <ul>
                       <li><%= link_to "About", about_path %></li>
                       <!--li><a href="#">Facebook</a></li-->
                       <!--li><a href="#">Twitter</a></li-->
                   </ul>
               </nav>
               <h2>Discover</h2>
               <nav>
                   <ul>
                       <li><a href="#">Everything</a></li>
                       <!--li><a href="#">Popular</a></li-->
                       <!--li><a href="#">Random</a></li-->
                   </ul>
               </nav>
               <h2>Trending</h2>
               <nav>
                   <ul>
                       <li><a href="#">Lorern</a></li>
                       <li><a href="#">Ipsum</a></li>
                       <li><a href="#">Sit Amet</a></li>
                   </ul>
               </nav>
           </div>
       </div>
       <div class="unit-80 mainContent">

       <%= yield %>
   </div>
   </div>

   <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
   <script>
       $(function(){
         $(".content").click(function(){
            window.location=$(this).find("a.postLink").attr("href");
            return false;
          });
        });

        $(function(){
            $(".content span").click(function(e){
              e.stopPropagation();
              //show tooltip
            });
        });

        $(function(){
            $(".action").click(function(e){
              e.stopPropagation();
              //show tooltip
            });
        });

    </script
</body>
</html>

app/views/shared/_big_grid_view.html.erb
<article class="units-split">

    <% project_collection.each do |project| %>

    <div class="content unit-50">
        <%= link_to project, class: "postLink" do %>
        <div class="contentImg"><%= image_tag project.image %></div>
        <div class="content-inner">
            <div class="unit-80">
                <header class="contentHash">

                <% project.reactions.any? %>
                    <% project.reactions.each do |reaction| %>
                    <%= link_to reaction.name, reaction_tagged_url(:reaction => reaction.name), class: "hash" %>
                <% end %>

                </header>

                <h1><span><%= project.header %></span></h1>

                <p class="textRed">

                    <% project.tags.any? %>
                    <span><%= project.tags.map{|tag| link_to tag.name, tagged_url(:tag => tag.name)}.join(', ').html_safe %></span>
                </p>
            </div>
            <div class="unit-20">
                <ul class="action">
                    <li class="wlButton"><%= render '/shared/wishlist_form', :project => project %><br>
                        <div class="count"><span id="wishlisted_by_<%= project.id %>"><%= project.wishlists.count %></span></div></li>
                    <li class="likePost"><%= render '/shared/like_form', :project => project %><br>
                        <div class="count"><span id="liked_by_<%= project.id %>"><%= project.likes.count %></span></div>
                    </li>
                </ul>
            </div>
        </div>
        <footer>
            <div class="footer-inner">
                <p class="auther"><a href="#"><%= image_tag project.user.avatar, size: '11' %><%= project.user.username %></a></p>
                <time>
                    <%= project.created_at.strftime("%b %d '%y at %H:%M") %>
                </time>
            </div>
        </footer>
        <% end %>
    </div>

    <% end %>

app/views/shared/_like_form.html.erb
 <% if user_signed_in? %>
	<div id="like_form_<%= project.id %>">
	  <% if current_user.likes_project?(project) %>
	    <%= render '/projects/unlike', project: project %>
	  <% else %>
	    <%= render '/projects/like', project: project %>
	  <% end %>
	</div>
<% end %>

app/views/shared/_wishlist_form.html.erb
 <% if user_signed_in? %>
	<div id="wishlist_form_<%= project.id %>">
	  <% if !!current_user.added_project_to_wishlist?(project) %>
	    <%= render '/projects/remove_from_wishlist', project: project %>
	  <% else %>
	  	<%= render '/projects/add_to_wishlist', project: project %>
	  <% end %>
	</div>
<% end %>